// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `IServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <IServer.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_server_IServer_ids[2] =
{
    "::Ice::Object",
    "::server::IServer"
};
const ::std::string iceC_server_IServer_ops[] =
{
    "addMusic",
    "addMusicPath",
    "display",
    "findByAlbum",
    "findByArtist",
    "findById",
    "findByName",
    "getPlaylist",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "playMusic",
    "remove",
    "stopMusic"
};
const ::std::string iceC_server_IServer_addMusic_name = "addMusic";
const ::std::string iceC_server_IServer_addMusicPath_name = "addMusicPath";
const ::std::string iceC_server_IServer_playMusic_name = "playMusic";
const ::std::string iceC_server_IServer_stopMusic_name = "stopMusic";
const ::std::string iceC_server_IServer_remove_name = "remove";
const ::std::string iceC_server_IServer_findById_name = "findById";
const ::std::string iceC_server_IServer_findByName_name = "findByName";
const ::std::string iceC_server_IServer_findByArtist_name = "findByArtist";
const ::std::string iceC_server_IServer_findByAlbum_name = "findByAlbum";
const ::std::string iceC_server_IServer_display_name = "display";
const ::std::string iceC_server_IServer_getPlaylist_name = "getPlaylist";

}

bool
server::IServer::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_server_IServer_ids, iceC_server_IServer_ids + 2, s);
}

::std::vector<::std::string>
server::IServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_server_IServer_ids[0], &iceC_server_IServer_ids[2]);
}

::std::string
server::IServer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
server::IServer::ice_staticId()
{
    static const ::std::string typeId = "::server::IServer";
    return typeId;
}

/// \cond INTERNAL
bool
server::IServer::_iceD_addMusic(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    ::std::string iceP_artist;
    ::std::string iceP_album;
    istr->readAll(iceP_name, iceP_artist, iceP_album);
    inS.endReadParams();
    this->addMusic(::std::move(iceP_name), ::std::move(iceP_artist), ::std::move(iceP_album), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_addMusicPath(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    bool ret = this->addMusicPath(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_playMusic(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_id;
    istr->readAll(iceP_id);
    inS.endReadParams();
    this->playMusic(iceP_id, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_stopMusic(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->stopMusic(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_remove(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_id;
    istr->readAll(iceP_id);
    inS.endReadParams();
    bool ret = this->remove(iceP_id, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_findById(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_id;
    istr->readAll(iceP_id);
    inS.endReadParams();
    Music ret = this->findById(iceP_id, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_findByName(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    playlist ret = this->findByName(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_findByArtist(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_artist;
    istr->readAll(iceP_artist);
    inS.endReadParams();
    playlist ret = this->findByArtist(::std::move(iceP_artist), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_findByAlbum(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_album;
    istr->readAll(iceP_album);
    inS.endReadParams();
    playlist ret = this->findByAlbum(::std::move(iceP_album), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_display(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->display(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_getPlaylist(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    playlist ret = this->getPlaylist(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_server_IServer_ops, iceC_server_IServer_ops + 15, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_server_IServer_ops)
    {
        case 0:
        {
            return _iceD_addMusic(in, current);
        }
        case 1:
        {
            return _iceD_addMusicPath(in, current);
        }
        case 2:
        {
            return _iceD_display(in, current);
        }
        case 3:
        {
            return _iceD_findByAlbum(in, current);
        }
        case 4:
        {
            return _iceD_findByArtist(in, current);
        }
        case 5:
        {
            return _iceD_findById(in, current);
        }
        case 6:
        {
            return _iceD_findByName(in, current);
        }
        case 7:
        {
            return _iceD_getPlaylist(in, current);
        }
        case 8:
        {
            return _iceD_ice_id(in, current);
        }
        case 9:
        {
            return _iceD_ice_ids(in, current);
        }
        case 10:
        {
            return _iceD_ice_isA(in, current);
        }
        case 11:
        {
            return _iceD_ice_ping(in, current);
        }
        case 12:
        {
            return _iceD_playMusic(in, current);
        }
        case 13:
        {
            return _iceD_remove(in, current);
        }
        case 14:
        {
            return _iceD_stopMusic(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_addMusic(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_name, const ::std::string& iceP_artist, const ::std::string& iceP_album, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_server_IServer_addMusic_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name, iceP_artist, iceP_album);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_addMusicPath(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_IServer_addMusicPath_name);
    outAsync->invoke(iceC_server_IServer_addMusicPath_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_playMusic(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_id, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_server_IServer_playMusic_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_id);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_stopMusic(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_IServer_stopMusic_name);
    outAsync->invoke(iceC_server_IServer_stopMusic_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_remove(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, int iceP_id, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_IServer_remove_name);
    outAsync->invoke(iceC_server_IServer_remove_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_id);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_findById(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<Music>>& outAsync, int iceP_id, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_IServer_findById_name);
    outAsync->invoke(iceC_server_IServer_findById_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_id);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_findByName(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<playlist>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_IServer_findByName_name);
    outAsync->invoke(iceC_server_IServer_findByName_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_findByArtist(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<playlist>>& outAsync, const ::std::string& iceP_artist, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_IServer_findByArtist_name);
    outAsync->invoke(iceC_server_IServer_findByArtist_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_artist);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_findByAlbum(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<playlist>>& outAsync, const ::std::string& iceP_album, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_IServer_findByAlbum_name);
    outAsync->invoke(iceC_server_IServer_findByAlbum_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_album);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_display(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_server_IServer_display_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::IServerPrx::_iceI_getPlaylist(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<playlist>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_IServer_getPlaylist_name);
    outAsync->invoke(iceC_server_IServer_getPlaylist_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
server::IServerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<IServerPrx>();
}
/// \endcond

const ::std::string&
server::IServerPrx::ice_staticId()
{
    return IServer::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_server_IServer_addMusic_name = "addMusic";

const ::std::string iceC_server_IServer_addMusicPath_name = "addMusicPath";

const ::std::string iceC_server_IServer_playMusic_name = "playMusic";

const ::std::string iceC_server_IServer_stopMusic_name = "stopMusic";

const ::std::string iceC_server_IServer_remove_name = "remove";

const ::std::string iceC_server_IServer_findById_name = "findById";

const ::std::string iceC_server_IServer_findByName_name = "findByName";

const ::std::string iceC_server_IServer_findByArtist_name = "findByArtist";

const ::std::string iceC_server_IServer_findByAlbum_name = "findByAlbum";

const ::std::string iceC_server_IServer_display_name = "display";

const ::std::string iceC_server_IServer_getPlaylist_name = "getPlaylist";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::server::upCast(IServer* p) { return p; }

void
::IceProxy::server::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< IServer>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new IServer;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_addMusic(const ::std::string& iceP_name, const ::std::string& iceP_artist, const ::std::string& iceP_album, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_addMusic_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_addMusic_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        ostr->write(iceP_artist);
        ostr->write(iceP_album);
        result->endWriteParams();
        result->invoke(iceC_server_IServer_addMusic_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::server::IServer::end_addMusic(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_server_IServer_addMusic_name);
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_addMusicPath(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_IServer_addMusicPath_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_addMusicPath_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_addMusicPath_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_server_IServer_addMusicPath_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::server::IServer::end_addMusicPath(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_IServer_addMusicPath_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_playMusic(::Ice::Int iceP_id, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_playMusic_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_playMusic_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_id);
        result->endWriteParams();
        result->invoke(iceC_server_IServer_playMusic_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::server::IServer::end_playMusic(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_server_IServer_playMusic_name);
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_stopMusic(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_IServer_stopMusic_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_stopMusic_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_stopMusic_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_server_IServer_stopMusic_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::server::IServer::end_stopMusic(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_IServer_stopMusic_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_remove(::Ice::Int iceP_id, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_IServer_remove_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_remove_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_remove_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_id);
        result->endWriteParams();
        result->invoke(iceC_server_IServer_remove_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::server::IServer::end_remove(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_IServer_remove_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_findById(::Ice::Int iceP_id, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_IServer_findById_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_findById_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_findById_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_id);
        result->endWriteParams();
        result->invoke(iceC_server_IServer_findById_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::server::Music
IceProxy::server::IServer::end_findById(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_IServer_findById_name);
    ::server::Music ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_findByName(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_IServer_findByName_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_findByName_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_findByName_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_server_IServer_findByName_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::server::playlist
IceProxy::server::IServer::end_findByName(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_IServer_findByName_name);
    ::server::playlist ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_findByArtist(const ::std::string& iceP_artist, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_IServer_findByArtist_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_findByArtist_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_findByArtist_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_artist);
        result->endWriteParams();
        result->invoke(iceC_server_IServer_findByArtist_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::server::playlist
IceProxy::server::IServer::end_findByArtist(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_IServer_findByArtist_name);
    ::server::playlist ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_findByAlbum(const ::std::string& iceP_album, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_IServer_findByAlbum_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_findByAlbum_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_findByAlbum_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_album);
        result->endWriteParams();
        result->invoke(iceC_server_IServer_findByAlbum_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::server::playlist
IceProxy::server::IServer::end_findByAlbum(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_IServer_findByAlbum_name);
    ::server::playlist ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_display(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_display_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_display_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_server_IServer_display_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::server::IServer::end_display(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_server_IServer_display_name);
}

::Ice::AsyncResultPtr
IceProxy::server::IServer::_iceI_begin_getPlaylist(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_IServer_getPlaylist_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_IServer_getPlaylist_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_IServer_getPlaylist_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_server_IServer_getPlaylist_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::server::playlist
IceProxy::server::IServer::end_getPlaylist(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_IServer_getPlaylist_name);
    ::server::playlist ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::server::IServer::_newInstance() const
{
    return new IServer;
}
/// \endcond

const ::std::string&
IceProxy::server::IServer::ice_staticId()
{
    return ::server::IServer::ice_staticId();
}

server::IServer::~IServer()
{
}

/// \cond INTERNAL
::Ice::Object* server::upCast(IServer* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_server_IServer_ids[2] =
{
    "::Ice::Object",
    "::server::IServer"
};

}

bool
server::IServer::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_server_IServer_ids, iceC_server_IServer_ids + 2, s);
}

::std::vector< ::std::string>
server::IServer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_server_IServer_ids[0], &iceC_server_IServer_ids[2]);
}

const ::std::string&
server::IServer::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
server::IServer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::server::IServer";
    return typeId;
#else
    return iceC_server_IServer_ids[1];
#endif
}

/// \cond INTERNAL
bool
server::IServer::_iceD_addMusic(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    ::std::string iceP_artist;
    ::std::string iceP_album;
    istr->read(iceP_name);
    istr->read(iceP_artist);
    istr->read(iceP_album);
    inS.endReadParams();
    this->addMusic(iceP_name, iceP_artist, iceP_album, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_addMusicPath(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    bool ret = this->addMusicPath(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_playMusic(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_id;
    istr->read(iceP_id);
    inS.endReadParams();
    this->playMusic(iceP_id, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_stopMusic(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->stopMusic(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_remove(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_id;
    istr->read(iceP_id);
    inS.endReadParams();
    bool ret = this->remove(iceP_id, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_findById(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_id;
    istr->read(iceP_id);
    inS.endReadParams();
    Music ret = this->findById(iceP_id, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_findByName(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    playlist ret = this->findByName(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_findByArtist(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_artist;
    istr->read(iceP_artist);
    inS.endReadParams();
    playlist ret = this->findByArtist(iceP_artist, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_findByAlbum(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_album;
    istr->read(iceP_album);
    inS.endReadParams();
    playlist ret = this->findByAlbum(iceP_album, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_display(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->display(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::IServer::_iceD_getPlaylist(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    playlist ret = this->getPlaylist(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_server_IServer_all[] =
{
    "addMusic",
    "addMusicPath",
    "display",
    "findByAlbum",
    "findByArtist",
    "findById",
    "findByName",
    "getPlaylist",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "playMusic",
    "remove",
    "stopMusic"
};

}

/// \cond INTERNAL
bool
server::IServer::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_server_IServer_all, iceC_server_IServer_all + 15, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_server_IServer_all)
    {
        case 0:
        {
            return _iceD_addMusic(in, current);
        }
        case 1:
        {
            return _iceD_addMusicPath(in, current);
        }
        case 2:
        {
            return _iceD_display(in, current);
        }
        case 3:
        {
            return _iceD_findByAlbum(in, current);
        }
        case 4:
        {
            return _iceD_findByArtist(in, current);
        }
        case 5:
        {
            return _iceD_findById(in, current);
        }
        case 6:
        {
            return _iceD_findByName(in, current);
        }
        case 7:
        {
            return _iceD_getPlaylist(in, current);
        }
        case 8:
        {
            return _iceD_ice_id(in, current);
        }
        case 9:
        {
            return _iceD_ice_ids(in, current);
        }
        case 10:
        {
            return _iceD_ice_isA(in, current);
        }
        case 11:
        {
            return _iceD_ice_ping(in, current);
        }
        case 12:
        {
            return _iceD_playMusic(in, current);
        }
        case 13:
        {
            return _iceD_remove(in, current);
        }
        case 14:
        {
            return _iceD_stopMusic(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
server::IServer::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< IServer, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
server::IServer::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< IServer, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
server::_icePatchObjectPtr(IServerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = IServerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(IServer::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
